### ISSUE TITLE
Where is the .xinitrc (:

### ISSUE THREAD

**Issue by refaatcrafts** [Edesem/Suckless#2]

**Comment by Aman1337g** [comment]
It is present in /etc/X11/xinit/

**Comment by Edesem** [comment]
This repo is specifically for suckless programs, your .xinitrc should be seperate and managed by yourself to have the programs that you need to load first.

At the very least it should follow the format of 
```
exec {Program} &
exec {Program} &
...
...
exec dwm
```

with `exec dwn` having no ampersand following it.
